development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: rails-chat-tutorial_development

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:165616c21eb2fde3b616318002f48f94@pearlfish.redistogo.com:9231/
  channel_prefix: rails-chat-tutorial_production
